name: Update packages versions

on:
  create:
    branches:
      - "release/**"
      - "hotfix/**"

jobs:
  change-version:
    name: "Update packages versions"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: '${{ github.token }}'

      - name: Filter changes and update versions
        id: update-versions
        run: |
          VERSION=$(echo "${GITHUB_REF#refs/heads/}" | sed 's/[^0-9.]*//g')
          sed -i "s/\(\"version\":\).*/\1 \"$VERSION\",/g" packages/*/package.json
          git diff --exit-code --quiet || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'ONLYOFFICE'
          author_email: '${{secrets.MAIL}}'
          message: 'Update version in package.json'
          add: '.'
          cwd: '.'

