name: Update packages versions

on:
  create:
    branches:
      - "release/**"
      - "hotfix/**"

jobs:
  change-version:
    name: "Update packages versions"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: '${{ github.token }}'

      - name: Filter changes and update versions
        id: update-versions
        run: |
              echo VERSION=$(echo "${GITHUB_REF#refs/heads/}" | sed 's/[^0-9.]*//g') >> $GITHUB_ENV
              sed -i "s/\(\"version\":\).*/\1 \"${{env.VERSION}}\",/g" packages/*/package.json
              git diff --exit-code --quiet || echo "changed=true" >> $GITHUB_OUTPUT
              echo $VERSION
              echo ${{env.VERSION}}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: Update version in packages.json for v${{ env.VERSION }}

